Script started on 2020-06-13 23:47:57-06:00
]0;priyavart.rajain1@csa2:~/Documentspriyavart.rajain1@csa2:~/Documents$ ./assign5 4 gcc assign5.s -o assign5 -g3[2Pm4 assign5.asm > assign5.s
]0;priyavart.rajain1@csa2:~/Documentspriyavart.rajain1@csa2:~/Documents$ m4 assign5.asm > assign5.s[14P./assign5 4 gcc assign5.s -o assign5 -g3
]0;priyavart.rajain1@csa2:~/Documentspriyavart.rajain1@csa2:~/Documents$ gcc assign5.s -o assign5 -g3[2Pm4 assign5.asm > assign5.s[14P./assign5 4 
3  8  2  3  
3  7  8  2  
4  3  0  9  
8  3  2  2  
Enter a column number(0 to N) to sort by    0
3  8  2  3  
3  7  8  2  
4  3  0  9  
8  3  2  2  
Press 0 to quit the program now.
Press 1  to continue sorting.  1
Enter a column number(0 to N) to sort by    2
3  8  0  3  
3  7  2  2  
4  3  2  9  
8  3  8  2  
Press 0 to quit the program now.
Press 1  to continue sorting.  0
Enter a column number(0 to N) to sort by    0
3  8  0  3  
3  7  2  2  
4  3  2  9  
8  3  8  2  
Press 0 to quit the program now.
Press 1  to continue sorting.  0
]0;priyavart.rajain1@csa2:~/Documentspriyavart.rajain1@csa2:~/Documents$ ./assign5 4 [1P 6 
3  8  5  9  2  3  
3  0  1  1  5  8  
4  2  2  4  3  5  
4  1  0  0  1  7  
1  4  8  5  0  0  
7  4  8  2  3  2  
Enter a column number(0 to N) to sort by    2
3  8  0  9  2  3  
3  0  1  1  5  8  
4  2  2  4  3  5  
4  1  5  0  1  7  
1  4  8  5  0  0  
7  4  8  2  3  2  
Press 0 to quit the program now.
Press 1  to continue sorting.  ^[[A    1
Enter a column number(0 to N) to sort by    0
1  8  0  9  2  3  
3  0  1  1  5  8  
3  2  2  4  3  5  
4  1  5  0  1  7  
4  4  8  5  0  0  
7  4  8  2  3  2  
Press 0 to quit the program now.
Press 1  to continue sorting.  0
]0;priyavart.rajain1@csa2:~/Documentspriyavart.rajain1@csa2:~/Documents$ 0[Kquit[K[K[K[Kwxit[K[K[K[Kexit
exit

Script done on 2020-06-13 23:48:54-06:00
